
FROM elixir:1.14

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

RUN apt-get update && apt-get install -y inotify-tools

RUN mix archive.install hex phx_new 1.6.0 --force

COPY . .

RUN mix deps.get

RUN mix compile
EXPOSE 4000
CMD ["mix", "phx.server"]
